//vegan implementation is needed since spoonacular don't support it,

export function winePairingKeywords(){
    const pairings = [ 
        "salmon",
        "steak",
        "salad",
        "beef",
        "pork",
        "fish",
        "tuna",
        "hamburger",
        "carbonara",
        "pizza",
        "rabbit",
        "shark",
        "octopus",
        "lobster",
        "chicken",
        "chinese",
        "italian",
        "mexican",
        "asian",
        "german",
        "african",
        "sushi",
        "seafood",
        "lamb",
        "stew",
        "omelette",
        "prawn",
        "hummus",
        "caviar",
        "cod",
        "swordfish",
        "ham",
        "perch",
        "popcorn",
        "chocolate",
        "ice cream",
        "grapes",
        "fruit",
    ]
}
